apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kush2106/backend_image:v1.0.0
          imagePullPolicy: Always
          command: ["python", "run.py"]
          ports:
            - containerPort: 8000